blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DiscusiÃ³n del Equipo
    url: https://github.com/utriper/discussions
    about: Para preguntas generales y discusiones del equipo
  - name: ğŸ› Reporte de Bug
    url: https://github.com/utriper/com.utriper.bugs/issues/new?labels=bug&template=bug_report.md
    about: Reportar un error o problema
  - name: ğŸ“– DocumentaciÃ³n
    url: https://github.com/utriper/com.utriper.docs
    about: Consultar documentaciÃ³n del proyecto
